package gui;

import Quanly.DiemSEV;
import Thuoctinh.Bangdiem;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class JFBangdiem extends javax.swing.JFrame {
    
    Bangdiem bangdiem = null;
    DiemSEV diemSEV = null;
    DefaultTableModel defaultTableModel = null;

    /**
     * Creates new form JFBangdiem
     */
    public JFBangdiem() throws SQLException {
        initComponents();
        bangdiem = new Bangdiem();
        diemSEV = new DiemSEV();
        defaultTableModel = new DefaultTableModel();
        jtbBangdiem.setModel(defaultTableModel);
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Họ và tên");
        defaultTableModel.addColumn("Điểm môn 1");
        defaultTableModel.addColumn("Điểm môn 2");
        defaultTableModel.addColumn("Điểm môn 3");
        
        List<Bangdiem> bangdiems = diemSEV.getAll();
        for (Bangdiem bangdiem : bangdiems) {
            defaultTableModel.addRow(new Object[]{bangdiem.getId(), bangdiem.getHvt(), bangdiem.getMon1(),
                bangdiem.getMon2(), bangdiem.getMon3()});
        }
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBangdiem = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        txtMon1 = new javax.swing.JTextField();
        txtMon2 = new javax.swing.JTextField();
        txtMon3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtHvt = new javax.swing.JTextField();
        btnLammoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMDangxuat = new javax.swing.JMenuItem();
        jMthoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("                                       Bảng điểm sinh viên");

        jtbBangdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbBangdiem);

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 153, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtMon1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMon1MouseClicked(evt);
            }
        });

        txtMon2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMon2MouseClicked(evt);
            }
        });

        txtMon3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMon3MouseClicked(evt);
            }
        });
        txtMon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMon3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Họ và tên");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Môn 1");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Môn 2");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Môn 3");

        txtId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtHvt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtHvt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHvtMouseClicked(evt);
            }
        });
        txtHvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHvtActionPerformed(evt);
            }
        });

        btnLammoi.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnLammoi.setForeground(new java.awt.Color(153, 0, 153));
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnSua.setForeground(new java.awt.Color(204, 204, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(204, 0, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapnhat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCapnhat.setForeground(new java.awt.Color(0, 0, 204));
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMDangxuat.setText("Đăng xuất");
        jMDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDangxuatActionPerformed(evt);
            }
        });
        jMenu1.add(jMDangxuat);

        jMthoat.setText("Thoát");
        jMthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMthoatActionPerformed(evt);
            }
        });
        jMenu1.add(jMthoat);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(btnThem))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnCapnhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua)
                        .addGap(43, 43, 43)
                        .addComponent(btnXoa)
                        .addGap(40, 40, 40)
                        .addComponent(btnLammoi)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHvt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMon2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMon3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnLammoi)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        bangdiem.setHvt(txtHvt.getText());
        bangdiem.setId(Integer.parseInt(txtId.getText()));
        bangdiem.setMon1(txtMon1.getText());
        bangdiem.setMon2(txtMon2.getText());
        bangdiem.setMon3(txtMon3.getText());
        diemSEV.addDiem(bangdiem);
        JOptionPane.showMessageDialog(this, "Thêm điểm thành công");
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        bangdiem.setHvt(txtHvt.getText());
        bangdiem.setId(Integer.parseInt(txtId.getText()));
        bangdiem.setMon1(txtMon1.getText());
        bangdiem.setMon2(txtMon2.getText());
        bangdiem.setMon3(txtMon3.getText());
        diemSEV.updateBangdiem(bangdiem);
//        JOptionPane.showMessageDialog(this, "Sửa điểm thành công");
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = jtbBangdiem.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn user trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int luachon = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa không?");
            if (luachon == JOptionPane.YES_OPTION) {
                int id = Integer.valueOf(String.valueOf(jtbBangdiem.getValueAt(row, 0)));
                diemSEV.delDiem(id);
                defaultTableModel.setRowCount(0);
                List<Bangdiem> bangdiems = diemSEV.getAll();
                for (Bangdiem bangdiem : bangdiems) {
                    defaultTableModel.addRow(new Object[]{bangdiem.getId(), bangdiem.getHvt(),
                        bangdiem.getMon1(), bangdiem.getMon2(), bangdiem.getMon3()});
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        defaultTableModel.setRowCount(0);
        List<Bangdiem> bangdiems = diemSEV.getAll();
        for (Bangdiem bangdiem : bangdiems) {
            defaultTableModel.addRow(new Object[]{bangdiem.getId(), bangdiem.getHvt(),
                bangdiem.getMon1(), bangdiem.getMon2(), bangdiem.getMon3()});
        }
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        int row = jtbBangdiem.getSelectedRow();
        int id = Integer.valueOf(String.valueOf(jtbBangdiem.getValueAt(row, 0)));
        bangdiem = diemSEV.getDiembyID(id);
        
        txtId.setText(String.valueOf(bangdiem.getId()));
        txtHvt.setText(bangdiem.getHvt());
        txtMon1.setText(bangdiem.getMon1());
        txtMon2.setText(bangdiem.getMon2());
        txtMon3.setText(bangdiem.getMon3());
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtHvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHvtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHvtActionPerformed

    private void txtHvtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHvtMouseClicked
        if (txtHvt.getText().equals(txtHvt.getText())) {
            txtHvt.setText("");
            txtHvt.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtHvtMouseClicked

    private void txtMon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMon1MouseClicked
        if (txtMon1.getText().equals(txtMon1.getText())) {
            txtMon1.setText("");
            txtMon1.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtMon1MouseClicked

    private void txtMon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMon2MouseClicked
        if (txtMon2.getText().equals(txtMon2.getText())) {
            txtMon2.setText("");
            txtMon2.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtMon2MouseClicked

    private void txtMon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMon3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMon3ActionPerformed

    private void txtMon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMon3MouseClicked
        if (txtMon3.getText().equals(txtMon3.getText())) {
            txtMon3.setText("");
            txtMon3.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtMon3MouseClicked

    private void jMDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDangxuatActionPerformed
        Dangnhap dangnhap = new Dangnhap();
        DangXuat.logOut(this, dangnhap);
    }//GEN-LAST:event_jMDangxuatActionPerformed

    private void jMthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMthoatActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jMthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBangdiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBangdiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBangdiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBangdiem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFBangdiem().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFBangdiem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMDangxuat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMthoat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbBangdiem;
    private javax.swing.JTextField txtHvt;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMon1;
    private javax.swing.JTextField txtMon2;
    private javax.swing.JTextField txtMon3;
    // End of variables declaration//GEN-END:variables

}
